### Parallel Cluster ###
# Create Parallel Cluster resources
Region: us-east-1
Image:
  Os: alinux2
Tags:
  - Key: 'environment'
    Value: ###Replace with CFNStackName output from the CloudFormation stack.
  - Key: 'pcluster version'
    Value: ###Replace with ParallelClusterVersion output from the CloudFormation stack.
HeadNode:
  InstanceType: t2.micro
  Networking:
    SubnetId: ###Replace with ManagementZone1SubnetId output from the CloudFormation stack.
    ElasticIp: false
    AdditionalSecurityGroups:
      - ###Replace with ManagementZoneSecurityGroup output from the CloudFormation stack.
  Ssh:
    KeyName: ###Replace with SSHKeyName output from the CloudFormation stack.
  LocalStorage:
    RootVolume:
      Size: 50
      VolumeType: gp3
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    S3Access:
      - BucketName: ###Replace with CampaignStorageBucket output from the CloudFormation stack.
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 5
    EnableMemoryBasedScheduling: true
    Database:
      Uri: ###Replace with RDSURI output from the CloudFormation stack.
      UserName: ###Replace with RDSDatabaseAdminUsername output from the CloudFormation stack.
      PasswordSecretArn: ###Replace with RDSDatabaseAdminPasswordSecret output from the CloudFormation stack.
      DatabaseName: ###Replace with RDSDatabaseName output from the CloudFormation stack.
  SlurmQueues:
    - Name: cpu
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: cpu
          InstanceType: c5.large
          MinCount: 0
          MaxCount: 2
          DisableSimultaneousMultithreading: false
          Efa:
            Enabled: False
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 100
            VolumeType: gp3
          EphemeralVolume:
            MountDir: /localscratch
      Networking:
        SubnetIds:
          - ###Replace with ComputeZoneSubnetId output from the CloudFormation stack.
        PlacementGroup:
          Enabled: false
        AdditionalSecurityGroups:
          - ###Replace with ComputeZoneSecurityGroup output from the CloudFormation stack.
      Iam:
        S3Access:
          - BucketName: ###Replace with ampaignStorageBucket output from the CloudFormation stack.
    - Name: gpu
      CapacityType: ONDEMAND
      ComputeResources:
        - Name: gpu
          Instances:
            - InstanceType: g4dn.xlarge
          MinCount: 0
          MaxCount: 2
          DisableSimultaneousMultithreading: false
          Efa:
            Enabled: False
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 100
            VolumeType: gp3
          EphemeralVolume:
            MountDir: /localscratch
      Networking:
        SubnetIds:
          - ###Replace with ComputeZoneSubnetId output from the CloudFormation stack.
        PlacementGroup:
          Enabled: false
        AdditionalSecurityGroups:
          - ###Replace with ComputeZoneSecurityGroup output from the CloudFormation stack.
      Iam:
        S3Access:
          - BucketName: ###Replace with ampaignStorageBucket output from the CloudFormation stack.
SharedStorage:
  - Name: fsxshared
    StorageType: FsxLustre
    MountDir: /scratch
    FsxLustreSettings:
      FileSystemId: ###Replace with FSxForLustreFileSystem output from the CloudFormation stack
  - Name: efsshared
    StorageType: Efs
    MountDir: /group
    EfsSettings:
      FileSystemId: ###Replace with EFSFileSystem output from the CloudFormation stack
  - Name: ebsshared
    StorageType: Ebs
    MountDir: /users
    EbsSettings:
      VolumeType: gp3
      Encrypted: true
      #DeletionPolicy: Retain
      Size: 100
Monitoring:
  Logs:
    CloudWatch:
      Enabled: true
      RetentionInDays: 30
      #DeletionPolicy: Retain
  Dashboards:
    CloudWatch:
      Enabled: true